### ISSUE TITLE
Plan for EDMF calibration pipeline for ClimaAtmos.jl

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CalibrateAtmos.jl#1]
## Purpose
The goal is to have calibration scripts for EDMF in ClimaAtmos.jl. This is an equivalent of https://github.com/CliMA/CalibrateEDMF.jl for the standalone EDMF repository.

## Cost/Benefits/Risks
Cost/Risk: The initial cost and risk are minimal. We will be mostly porting over and adapting the scripts from CalibrateEDMF.jl

Benefits: We need a calibration pipeline for EDMF in the ClimaAtmos model. The EDMF code is being refactored. It would be extremely helpful to be able to calibrate the refactored code to see if we can recover the current model results. 

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: TBD
- Collaborators: @trontrytel , @odunbar, @costachris, @nefrathenrici 
- Reviewers: @haakon-e, @szy21 

## Components
(Describe the main components of the software solution)

## Inputs
(Describe the inputs to the software solution)

## Results and deliverables
- [ ] Calibrate a ClimaAtmos.jl SCM EDMF Bomex case (one of the cases we run in the CI) with the data from the standalone TurbulenceConvection.jl model.
- [ ] Add more cases to calibration pipeline.
- [ ] Create a semi-automatic way to trigger calibrations. (This would help with the code refactoring of EDMF)

## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [ ] Retire the namelist interface of EDMF in ClimaAtmos and move to toml and config file structure. See the discussion here: https://github.com/CliMA/ClimaAtmos.jl/issues/1259, PR https://github.com/CliMA/CLIMAParameters.jl/pull/103 (@nefrathenrici , @trontrytel)
- [x] #2
- [ ] Port over the CalibrateEDMF scripts using the toml files (@costachris , @haakon-e)
- [ ] Modify CalibrateEDMF framework to read `hdf5` output from CA (instead of `TC.jl` netCDF stats files).
- [ ] Review the calibration workflow. Suggest tests and default settings, (@odunbar) 

## Proposed Delivery Date
(Your best estimate of the date this software solution will be completed)
