### ISSUE TITLE
O3.2.4 Moist Held-Suarez Perfect-Model Calibration

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/CalibrateAtmos.jl#17]
# The Climate Modeling Alliance
### Purpose

We will implement a pipeline to calibrate on the moist held-suarez experiment in ClimaAtmos. We will calibrate on the horizontal temperature gradient.
Once this is complete, we will generalize to a pipeline that can handle other cases.

### Cost/Benefits/Risks

Primary risk is developer time, but this will save us a lot of time for manual calibration in the long run.
### People and Personnel
 @szy21 @trontrytel 

### Components

- EKP interface: Configure EKP, construct the prior distribution, update ensemble
- HPC interface: this should be GPU and CPU compatible, ideally running on the cluster and the a100 server.
- Atmos interface: Configure and run the atmosphere model.
- Data processing utilities: Needed for constructing the observation map
- Visualization utilities: Used for comparing model output and determining useful information for the observation map

### Inputs

- EKP configuration: ensemble and iteration sizes
- Prior distribution TOML
- Observation map
- Steady-state restart file

### Results and Deliverables
- [x] Fully working and reproducible perfect-model calibration for moist held-suarez
- [x] Simple experiment configuration interface with tests
- [x] Inverse problem for the HS case

### Task Breakdown And Schedule
- [x] #5 
- [x] Create interface
- [x] Moist HS observation map
- [x] Demonstrate moist HS perfect model calibration

### CC
@tapios @simonbyrne @cmbengue

**Comment by tapios** [comment]
Looks good to time. Let's target running this on GPUs right away, to increase throughput. This may then also necessitate some GPU compatibility work for EKP (if it isn't already compatible).
